-- Automatically generated resource file. See content/prep_resources.rb
resource.AddFile("materials/aviator/aviator.vmt")
resource.AddFile("materials/aviator/aviator.vtf")
resource.AddFile("materials/aviator/aviator_envmap.vtf")
resource.AddFile("materials/gmcopter/hud/simcopter.png")
resource.AddFile("materials/gmcopter/sprites/light.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_2.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_2.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_artic.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_artic.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_cockpit.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_cockpit.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_desert.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_desert.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_forest.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_forest.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_glass.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_glass.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_glass_n.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_nightops.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_nightops.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_pacific.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_pacific.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_rotor.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_rotor.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_tail.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_woodland.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/ah-1 cobra_woodland.vtf")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/blur.vmt")
resource.AddFile("materials/models/bf2/helicopters/ah-1 cobra/blur.vtf")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie.vmt")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie.vtf")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie_cockpit.vmt")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie_cockpit.vtf")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie_glass.vmt")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie_glass.vtf")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie_interior.vmt")
resource.AddFile("materials/models/bf2/helicopters/mh-53j pave low iiie/mh-53j pave low iiie_interior.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28.vmt")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_cockpit.vmt")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_cockpit.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_cockpit_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_desert.vmt")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_desert.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_forest.vmt")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_forest.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_glass.vmt")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_glass.vtf")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_nightops.vmt")
resource.AddFile("materials/models/bf2/helicopters/mil mi-28/mil mi-28_nightops.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.vmt")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_cockpit.vmt")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_cockpit.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_cockpit_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_desert.vmt")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_desert.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_forest.vmt")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_forest.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_glass.vmt")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_glass.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_nightops.vmt")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_nightops.vtf")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wreck.vmt")
resource.AddFile("materials/models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wreck.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10.vmt")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_cockpit.vmt")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_cockpit.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_cockpit_bump.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_desert.vmt")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_desert.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_forest.vmt")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_forest.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_glass.vmt")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_glass.vtf")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_nightops.vmt")
resource.AddFile("materials/models/bf2/helicopters/wz-10/wz-10_nightops.vtf")
resource.AddFile("materials/models/flyboi/blackhawk/blackhawk_glass_blade_color.vtf")
resource.AddFile("materials/models/flyboi/littlebird/blade.vmt")
resource.AddFile("materials/models/flyboi/littlebird/littlebird_col.vmt")
resource.AddFile("materials/models/flyboi/littlebird/littlebird_col.vtf")
resource.AddFile("materials/models/flyboi/littlebird/littlebird_nml.vtf")
resource.AddFile("materials/models/headset/combine_elite.tga")
resource.AddFile("materials/models/headset/headset.tga")
resource.AddFile("materials/models/headset/headset.vmt")
resource.AddFile("materials/models/headset/headset.vtf")
resource.AddFile("materials/models/headset/headset_n.vtf")
resource.AddFile("materials/vgui/entities/wac_hc_ah1z_viper.vmt")
resource.AddFile("materials/vgui/entities/wac_hc_ah1z_viper.vtf")
resource.AddFile("materials/vgui/entities/wac_hc_blackhawk_uh60.vmt")
resource.AddFile("materials/vgui/entities/wac_hc_blackhawk_uh60.vtf")
resource.AddFile("materials/vgui/entities/wac_hc_littlebird_ah6.vmt")
resource.AddFile("materials/vgui/entities/wac_hc_littlebird_ah6.vtf")
resource.AddFile("materials/vgui/entities/wac_hc_littlebird_mh6.vmt")
resource.AddFile("materials/vgui/entities/wac_hc_littlebird_mh6.vtf")
resource.AddFile("materials/vgui/entities/wac_hc_mi28_havoc.vmt")
resource.AddFile("materials/vgui/entities/wac_hc_mi28_havoc.vtf")
resource.AddFile("materials/vgui/entities/wac_pl_c172.vmt")
resource.AddFile("materials/vgui/entities/wac_pl_c172.vtf")
resource.AddFile("materials/weltensturm/heli/rotorblur.vmt")
resource.AddFile("materials/weltensturm/heli/rotorblur.vtf")
resource.AddFile("materials/weltensturm/helihud/arrow.vmt")
resource.AddFile("materials/weltensturm/helihud/arrow.vtf")
resource.AddFile("materials/weltensturm/helihud/baredge.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/black.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/black_ph.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/bladeblur.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/c4_black.vmt")
resource.AddFile("materials/weltensturm/wac/helicopter/glass.vmt")
resource.AddFile("materials/weltensturm/wac/helicopter/glass.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/grey.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/hud_line_0.vmt")
resource.AddFile("materials/weltensturm/wac/helicopter/hud_line_0.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/hud_line_high.vmt")
resource.AddFile("materials/weltensturm/wac/helicopter/hud_line_high.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/hud_line_low.vmt")
resource.AddFile("materials/weltensturm/wac/helicopter/hud_line_low.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/instr_compass_1.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/mainblur.vtf")
resource.AddFile("materials/weltensturm/wac/helicopter/rt.vmt")
resource.AddFile("materials/weltensturm/wac/rockets/rocket_base.vmt")
resource.AddFile("materials/weltensturm/wac/rockets/rocket_base.vtf")
resource.AddFile("models/aviator/aviator.dx80.vtx")
resource.AddFile("models/aviator/aviator.dx90.vtx")
resource.AddFile("models/aviator/aviator.mdl")
resource.AddFile("models/aviator/aviator.phy")
resource.AddFile("models/aviator/aviator.sw.vtx")
resource.AddFile("models/aviator/aviator.vvd")
resource.AddFile("models/aviator/aviator.xbox.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_b.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_b.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_b.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_b.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_b.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_b.vvd")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g.vvd")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g1.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g1.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g1.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g1.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g1.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g1.vvd")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g2.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g2.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g2.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g2.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g2.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_g2.vvd")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_r.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_r.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_r.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_r.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_r.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_r.vvd")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar1.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar1.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar1.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar1.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar1.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar1.vvd")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar2.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar2.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar2.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar2.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar2.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_radar2.vvd")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_tr.dx80.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_tr.dx90.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_tr.mdl")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_tr.phy")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_tr.sw.vtx")
resource.AddFile("models/bf2/helicopters/ah-1 cobra/ah1z_tr.vvd")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_b.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_b.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_b.mdl")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_b.phy")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_b.sw.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_b.vvd")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_r.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_r.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_r.mdl")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_r.phy")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_r.sw.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_r.vvd")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_tr.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_tr.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_tr.mdl")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_tr.phy")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_tr.sw.vtx")
resource.AddFile("models/bf2/helicopters/mh-53j pave low iiie/mh53_tr.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_b.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_b.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_b.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_b.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_b.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_b.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g1.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g1.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g1.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g1.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g1.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g1.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g2.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g2.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g2.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g2.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g2.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_g2.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_r.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_r.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_r.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_r.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_r.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_r.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_radar1.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_radar1.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_radar1.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_radar1.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_radar1.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_radar1.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_tr.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_tr.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_tr.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_tr.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_tr.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_tr.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w1.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w1.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w1.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w1.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w1.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w1.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w2.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w2.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w2.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w2.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w2.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mi28_w2.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_tailwheel.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_tailwheel.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_tailwheel.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_tailwheel.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_tailwheel.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_tailwheel.vvd")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_wheel.dx80.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_wheel.dx90.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_wheel.mdl")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_wheel.phy")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_wheel.sw.vtx")
resource.AddFile("models/bf2/helicopters/mil mi-28/mil mi-28_wheel.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_extras.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_extras.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_extras.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_extras.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_extras.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_extras.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_rotor.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_rotor.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_rotor.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_rotor.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_rotor.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_rotor.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_tail.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_tail.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_tail.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_tail.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_tail.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_tail.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wings.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wings.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wings.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wings.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wings.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh-60 blackhawk_wings.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_b.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_b.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_b.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_b.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_b.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_b.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_r.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_r.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_r.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_r.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_r.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_r.vvd")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_rr.dx80.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_rr.dx90.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_rr.mdl")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_rr.phy")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_rr.sw.vtx")
resource.AddFile("models/bf2/helicopters/uh-60 blackhawk/uh60_rr.vvd")
resource.AddFile("models/flyboi/littlebird/littlebirda_fb.dx80.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirda_fb.dx90.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirda_fb.mdl")
resource.AddFile("models/flyboi/littlebird/littlebirda_fb.phy")
resource.AddFile("models/flyboi/littlebird/littlebirda_fb.sw.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirda_fb.vvd")
resource.AddFile("models/flyboi/littlebird/littlebirdrotorm_fb.dx80.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirdrotorm_fb.dx90.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirdrotorm_fb.mdl")
resource.AddFile("models/flyboi/littlebird/littlebirdrotorm_fb.phy")
resource.AddFile("models/flyboi/littlebird/littlebirdrotorm_fb.sw.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirdrotorm_fb.vvd")
resource.AddFile("models/flyboi/littlebird/littlebirdt_fb.dx80.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirdt_fb.dx90.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirdt_fb.mdl")
resource.AddFile("models/flyboi/littlebird/littlebirdt_fb.phy")
resource.AddFile("models/flyboi/littlebird/littlebirdt_fb.sw.vtx")
resource.AddFile("models/flyboi/littlebird/littlebirdt_fb.vvd")
resource.AddFile("models/flyboi/littlebird/littlebirdt_fb_o.phy")
resource.AddFile("models/flyboi/littlebird/littlebird_fb.dx80.vtx")
resource.AddFile("models/flyboi/littlebird/littlebird_fb.dx90.vtx")
resource.AddFile("models/flyboi/littlebird/littlebird_fb.mdl")
resource.AddFile("models/flyboi/littlebird/littlebird_fb.phy")
resource.AddFile("models/flyboi/littlebird/littlebird_fb.sw.vtx")
resource.AddFile("models/flyboi/littlebird/littlebird_fb.vvd")
resource.AddFile("models/headsep/headset.dx80.vtx")
resource.AddFile("models/headsep/headset.dx90.vtx")
resource.AddFile("models/headsep/headset.mdl")
resource.AddFile("models/headsep/headset.phy")
resource.AddFile("models/headsep/headset.sw.vtx")
resource.AddFile("models/headsep/headset.vvd")
resource.AddFile("models/headsep/headset.xbox.vtx")
resource.AddFile("models/headset/headset.dx80.vtx")
resource.AddFile("models/headset/headset.dx90.vtx")
resource.AddFile("models/headset/headset.mdl")
resource.AddFile("models/headset/headset.phy")
resource.AddFile("models/headset/headset.sw.vtx")
resource.AddFile("models/headset/headset.vvd")
resource.AddFile("models/headset/headset.xbox.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1.dx80.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1.dx90.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1.mdl")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1.phy")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1.sw.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1.vvd")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_blurr.dx80.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_blurr.dx90.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_blurr.mdl")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_blurr.sw.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_blurr.vvd")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_br.dx80.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_br.dx90.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_br.mdl")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_br.phy")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_br.sw.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_br.vvd")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gun.dx80.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gun.dx90.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gun.mdl")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gun.phy")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gun.sw.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gun.vvd")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gunm.dx80.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gunm.dx90.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gunm.mdl")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gunm.phy")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gunm.sw.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_gunm.vvd")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_r.dx80.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_r.dx90.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_r.mdl")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_r.phy")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_r.sw.vtx")
resource.AddFile("models/weltensturm/wac/helicopter/ahx1_r.vvd")
resource.AddFile("models/weltensturm/wac/rockets/rocket01.dx80.vtx")
resource.AddFile("models/weltensturm/wac/rockets/rocket01.dx90.vtx")
resource.AddFile("models/weltensturm/wac/rockets/rocket01.mdl")
resource.AddFile("models/weltensturm/wac/rockets/rocket01.phy")
resource.AddFile("models/weltensturm/wac/rockets/rocket01.sw.vtx")
resource.AddFile("models/weltensturm/wac/rockets/rocket01.vvd")
resource.AddFile("sound/fsx/c172/c172_rpm2.wav")
resource.AddFile("sound/fsx/c172/xc172_rrpm1.wav")
resource.AddFile("sound/fsx/c172/xc172_rrpm2.wav")
resource.AddFile("sound/fsx/c172/xc172_startup.wav")
resource.AddFile("sound/helicoptervehicle/crashalarm.mp3")
resource.AddFile("sound/helicoptervehicle/helistart.mp3")
resource.AddFile("sound/helicoptervehicle/lowhealth.mp3")
resource.AddFile("sound/helicoptervehicle/minoralarm.mp3")
resource.AddFile("sound/helicoptervehicle/missilenearby.mp3")
resource.AddFile("sound/helicoptervehicle/missileshoot.mp3")
resource.AddFile("sound/wac/cannon/havoc_cannon_1p.wav")
resource.AddFile("sound/wac/cannon/havoc_cannon_3p.wav")
resource.AddFile("sound/wac/cannon/viper_cannon_1p.wav")
resource.AddFile("sound/wac/cannon/viper_cannon_3p.wav")
resource.AddFile("sound/wac/cannon/viper_cannon_rotate.wav")
resource.AddFile("sound/wac/heli/ah1_start.wav")
resource.AddFile("sound/wac/heli/ah1_start_idle.wav")
resource.AddFile("sound/wac/heli/bellinternal.wav")
resource.AddFile("sound/wac/heli/h6_start.wav")
resource.AddFile("sound/wac/heli/heli_loop_ext.wav")
resource.AddFile("sound/wac/heli/heli_loop_int.wav")
resource.AddFile("sound/wac/heli/jet_whine.wav")
resource.AddFile("sound/wac/heli/missilenearby.wav")
resource.AddFile("sound/wac/heli/uh60_loop.wav")
resource.AddFile("sound/wac/rocket_idle.wav")
resource.AddFile("sound/wac/tank/tank_shell_01.wav")
resource.AddFile("sound/wac/tank/tank_shell_02.wav")
resource.AddFile("sound/wac/tank/tank_shell_03.wav")
resource.AddFile("sound/wac/tank/tank_shell_04.wav")
resource.AddFile("sound/wac/tank/tank_shell_05.wav")
resource.AddFile("sound/wac/tank/tank_shell_metal_01.wav")
resource.AddFile("sound/wac/tank/tank_shell_metal_02.wav")
resource.AddFile("sound/wac/tank/tank_shell_metal_03.wav")
resource.AddFile("sound/wac/tank/tank_shell_metal_04.wav")
resource.AddFile("sound/warkanum/minigun_shoot.wav")
resource.AddFile("sound/warkanum/minigun_wind_stop.wav")
